spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    enabled: true
    encoding: utf-8
    mode: HTML5
  # 配置redis
  redis:
    host: 192.168.126.138
    # Redis服务器连接端口
    port: 6379
    # 连接超时时间（毫秒）
    timeout: 3000
    password:
    poolMaxTotal: 1000
    poolMaxIdle: 500
    poolMaxWait: 500
  #配置rabbitmq
  rabbitmq:
    host: 192.168.126.138
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        concurrency: 10 #消费者数量
        max-concurrency: 10
        prefetch: 1 #消费者从队列取的消息个数
        auto-startup: true
        default-requeue-rejected: true #消费失败后允许重试
    template:
      retry:
        enabled: true # 允许发送者重试
        initial-interval: 1000 # 1秒后重试
        max-attempts: 3 # 最多重试3次
        max-interval: 10000
        multiplier: 1.0 # 如果为2表名第一次等1秒，第二次等2秒，第三次等4秒。。。。。
  #资源静态化
  resources:
    add-mappings: true
    static-locations: classpath:/static/
    chain:
      cache: true
      enabled: true
      compressed: true
      html-application-cache: true
    cache:
      period: 3600
mybatis:
  type-aliases-package: com.znuel.seckill.domain
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 3000
  mapper-locations: classpath:com/znuel/seckill/dao/mapper/*.xml



